### PR TITLE
Pr

### PR DESCRIPTION
**Pull request by MrChico**

### CODE REVIEW

**Comment by mhhf** [comment]
is this a superset of the other pr?

**Comment by asymmetric** [comment]
Beautiful title.

**Comment by MrChico** [comment]
@mhhf not since some new stuff were added to the lev branch. Will need to do another rebase

**Comment by mhhf** [comment]
if @livnev gives his go i'm fine with a merge

**Comment by mhhf** [comment]
@MrChico can we move dach in to its own repo before merging it?

**Comment by MrChico** [comment]
@mhhf, we can point dss back to the `lev` branch, which doesn't contain it

**Comment by livnev** [comment]
I rebased on top of latest stuff here: https://github.com/dapphub/k-dss/pull/7

**Comment by mhhf** [comment]
closing in favor of #7

**Pull request closed without merging**
