### PR TITLE
Call depth rebased

### PR DESCRIPTION
**Pull request by livnev**
Rebased #18 onto `master`, @MrChico FYI

### CODE REVIEW

**Comment by livnev** [comment]
Rebased this onto master again.

**Comment by MrChico** [comment]
I don't think we should change the callDepth for `fess` and `flog` since they are correctly specified for the canonical solidity version. It would be much better to change the solidity assembly to match the solidity

**Comment by MrChico** [comment]
Especially since the `fess` succeeds without additiona thel VCallDepth assumption on the solidity version. Tried it just now.

**Comment by livnev** [comment]
Incorporated this into the `lev` branch.

**Pull request closed without merging**
